### ISSUE TITLE
too much php

### ISSUE THREAD

**Issue by krystalgamer** [pdsam/FEUP-LTW#6]
Looking at metrics 63% of the code is PHP and as defined by the International Standards git repositories should strive to have less than 0.1% of PHP code.

Health checks are a must after being exposed to this codebase.

**Comment by MPDR200011** [comment]
Unfortunately, this project is over and no further development will be done on it. However, we do welcome suggested changes. If you have a solution for this please make a pull request and we will review it.

**Comment by krystalgamer** [comment]
> no further development will be done on it
> we do welcome suggested changes

too many inconsistencies. buddy.
cyberpolice has been alerted and is on its way, godspeed.

**Comment by krystalgamer** [comment]
yo, you don't close me
